Update chunk names to all chunks and small text changes
BAUDOTlab/scDataPipeline pull request #47
Opened 2023-12-18 14:52 UTC by celinech

Almost all files are modified!
Minor impact on the pipeline ==> saved figures saved by the execution could be found under a new name.

2023-12-18 16:55 UTC, Rumengol requested changes
Overall I agree with the new names, however we should adopt a single naming convention, as we currently have three, sometimes overlapping in the same name:
- `kebab-case`
- `snake_case`
- `camelCase`

I would argue in favor of the snake_case, as it is both more readable than the camelCase and it less error prone than the kebab-case.

2023-12-18 16:55 UTC, Rumengol commented on 04_additionalControls.Rmd
> +}ssssssss
?

2023-12-19 08:07 UTC, celinech commented
I agree that I don't fit a single format.

1. However, I remember I've read that kebab-case is better suited for chunk names. I'm sorry, I can't find the source of it. And as the majority of the chunk names are in kebab-case, I would prefer to go for it, to not spend too much time on it.

2. Would you like to change these ?
    - get-topNmarkers, cluster-dimPlot-markers, cluster-dotPlot-markers, cluster-dotPlot-goi
topNmarkers is already a variable in the code.
DimPlot, FeaturePlot, ... are pre-existing functions from seurat.

2023-12-19 08:45 UTC, Rumengol commented
Let's go with kebab-case then, I don't see the logic but since it's for file names it shouldn't be an issue.

For references to existing variables/functions, I'd say we can keep them as they are.

2023-12-20 10:56 UTC, Rumengol approved these changes

2023-12-20 10:56 UTC, merged