Load params sanity check
BAUDOTlab/scDataPipeline pull request #80
Opened 2024-02-08 16:38 UTC by sevdarafatov

Checking  if all the files and directory paths exists and are valid:

If parameter doesn`t exist in the configuration file giving  **The " " is not provided message**

If parameter is given but path is non existent giving a message arising from normalizePath

2024-02-09 08:56 UTC, celinech requested changes

2024-02-09 08:56 UTC, celinech commented on .gitignore
Do not modify the .gitignore.
We need to keep the docker-compose.yml to share how to use it.
You could make a copy in your requirements to keep it as you want, and let a standard copy in the repository.

2024-02-09 08:56 UTC, celinech commented on load_parameters.R
It is good to check if the variable exists :+1: 
Can you add the existence of the path/file also ?
For instance, one could set the `PATH_ATLAS = "vhiameoivnaq"`
The current file will assign the variable with the value, but the directory doesn't exist :(

Doing both in the same branch and in the same PR makes sense. What do you think ?

2024-02-09 10:50 UTC, sevdarafatov commented on .gitignore
Okay!

2024-02-20 15:09 UTC, celinech commented on 08_DEG_analysis.Rmd
yes, right :+1:

2024-02-21 08:50 UTC, sevdarafatov commented on 00_pipeline_launcher.R
I think this part should be commented out? ""opt$options$input_list <- "cardioWT,cardioKO"

2024-02-21 08:55 UTC, merged