Feat fgsea
BAUDOTlab/scDataPipeline pull request #81
Opened 2024-02-20 14:31 UTC by sevdarafatov

- Using deseq2 csv files to do fgsea analysis
- Creating a new folder 10_fgsea_analysis
- Creating folders for Reactome, KEGG, GOCC, GOBB database results
- Saving csv outputs in these created folders separetely

2024-02-20 14:54 UTC, celinech requested changes

2024-02-20 14:54 UTC, celinech commented on 08_DEG_analysis.Rmd
> +```{r loading-libraries, include = FALSE}
It is recommended to not have multiple chunks with the same name.
At the beginning of the file, there is already a loading-libraries chunk. You could move the lines into that chunk.

2024-02-20 14:58 UTC, sevdarafatov commented on 08_DEG_analysis.Rmd
> +```{r loading-libraries, include = FALSE}
Actually --to not have the same named chunks I renamed mine. First one is load-libraries, next one loading-libraries

2024-02-21 08:00 UTC, celinech approved these changes

2024-02-21 08:00 UTC, merged